---
title: "Biomarker discoverty with Zeller_2014 data"
author: "Sehyun Oh"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Zeller_2014 data}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    number_sections: yes
    toc: yes
    toc_depth: 4
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(comment = "#>", 
                      collapse = TRUE, 
                      message = FALSE, 
                      warning = FALSE)
```

```{r echo=FALSE}
suppressPackageStartupMessages({
    library(lefser)
    library(microbiomeMarker)
    library(lefserBenchmarking)
    library(grid)
    library(VennDiagram)
    library(dplyr)
    library(ggplot2)
})

LEfSeZellerDir <- "~/Projects/lefserBenchmarking/data/LEfSe_Outputs/zeller14"
```

# Load data
```{r load_zeller14}
## Old cMD data in the lefser package
data(zeller14)
zeller14 <- zeller14[, zeller14$study_condition != "adenoma"]
```

# Run lefser
```{r zeller14_by_lefser}
zeller14$study_condition <- factor(zeller14$study_condition,
                                   levels = c("CRC", "control")) # re-levels

set.seed(1982)
res <- lefser(relativeAb(zeller14), 
              groupCol = "study_condition", 
              blockCol = "age_category")
lefserPlot(res)
```

# Run LEfSe
## From Docker
Format zeller14 as a LEfSe input:
```{r eval=FALSE}
source("~/Projects/lefserBenchmark/inst/scripts/zeller14_txt.R")
```

## From Docker
```{r}
col_names <- c('feature', 'log_hi_class_avg', 'class', 'lefse_docker_LDA', 'pval')
lefse_docker <- readr::read_tsv(
    file.path(LEfSeZellerDir, "zeller14.res"),
    col_names = FALSE, show_col_types = FALSE) %>% 
    magrittr::set_colnames(col_names) %>% 
    filter(!is.na(lefse_docker_LDA)) %>% 
    mutate(lefse_galaxy_LDA = ifelse(class == "control", -lefse_docker_LDA, lefse_docker_LDA),
           app_name = 'lefse_docker')

lefse_docker$feature <- lapply(lefse_docker$feature, function(x) {
    strsplit(x, "\\.") %>% unlist %>% tail(., 1)}) %>% unlist

head(lefse_docker)
```


## From Galaxy
```{r}
col_names <- c('feature', 'log_hi_class_avg', 'class', 'lefse_galaxy_LDA', 'pval')
lefse_galaxy <- readr::read_tsv(
    file.path(LEfSeZellerDir, "zeller14_LEfSe_Galaxy.res"),
    col_names = FALSE, show_col_types = FALSE) %>% 
    magrittr::set_colnames(col_names) %>% 
    filter(!is.na(lefse_galaxy_LDA)) %>% 
    mutate(lefse_galaxy_LDA = ifelse(class == "control", -lefse_galaxy_LDA, lefse_galaxy_LDA),
           app_name = 'lefse_galaxy')

head(lefse_galaxy)
```


## From Conda
```{r}
col_names <- c('feature', 'log_hi_class_avg', 'class', 'lefse_conda_LDA', 'pval')
lefse_conda <- readr::read_tsv(
    file.path(LEfSeZellerDir, "zeller14_LEfSe_Conda.res"),
    show_col_types = FALSE, col_names = FALSE) %>% 
    magrittr::set_colnames(col_names) %>% 
    filter(!is.na(lefse_conda_LDA)) %>%
    mutate(lefse_conda_LDA = ifelse(class == 'control', -lefse_conda_LDA, lefse_conda_LDA), 
           app_name = 'lefse_conda') %>% 
    arrange(lefse_conda_LDA)
    
head(lefse_conda)
```


# Run microbiomeMarker
```{r}
ps <- formatInput(zeller14, "phyloseq")

set.seed(1982)
mm_lefse <- run_lefse(
    ps,
    wilcoxon_cutoff = 0.05,
    group = "study_condition",
    subgroup = "age_category",
    kw_cutoff = 0.05,
    multigrp_strat = TRUE,
    lda_cutoff = 2
)

plot_ef_bar(mm_lefse)
```

```{r}
vectors <- marker_table(mm_lefse)$feature
vectors_updated <- lapply(vectors, function(x) {
    strsplit(x, "\\|") %>% unlist %>% tail(., 1)}) %>% unlist %>%
    stringr::str_replace(., "_p__.*$|_c__.*$|_o__.*$|_f__.*$|_g__.*$|_s__.*$", "")
vectors_updated
```


# Comparisons
```{r}
lefser_output <- res %>% 
    mutate(app_name = 'lefser') %>% 
    arrange(scores) %>% 
    rename(feature = Names, lefser_LDA = scores)
lefser_output$feature <- lapply(lefser_output$feature, function(x) {
    strsplit(x, "\\|") %>% unlist %>% tail(., 1)}) %>% unlist


combined_outputs <- bind_rows(lefse_conda, lefse_galaxy, lefser_output, lefse_docker) %>% 
    mutate(LDA = coalesce(lefse_conda_LDA, lefse_galaxy_LDA, lefser_LDA, lefse_docker_LDA))

combined_outputs %>% 
    count(app_name) %>% 
    ggplot(aes(app_name, n)) +
    geom_col() +
    geom_label(aes(label = n)) +
    ggtitle(
        'Number of significiant features identified by the different applications using lefse'
    )
```

```{r}
set1 <- lefse_conda$feature
set2 <- lefse_galaxy$feature
set3 <- lefse_docker$feature
set4 <- lefser_output$feature
set5 <- vectors_updated # biomarkers from microbiomeMarker
    
# grid.newpage()
# venn_object <- venn.diagram(
#     x = list(set1, set2, set3, set4),
#     category.names = c("lefse-conda", "lefse-galaxy", "lefse-docker", "lefser"),
#     filename = NULL
# )
# grid.draw(venn_object)

grid.newpage()
venn_object <- venn.diagram(
    x = list(set3, set4, set5),
    category.names = c("LEfSe", "lefser", "microbiomeMarker"),
    filename = NULL
)
grid.draw(venn_object)
```

